# Generated by Django 3.2.9 on 2021-11-17 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_auto_20211117_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='city',
            new_name='locality',
        ),
    ]
