# Generated by Django 3.2.9 on 2021-11-17 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_rename_city_vendorprofile_locality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='post_code',
            new_name='postal_code',
        ),
    ]
