# Generated by Django 3.2.9 on 2021-11-17 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_rename_post_code_vendorprofile_postal_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='brew/')),
            ],
            options={
                'verbose_name_plural': 'Brews',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='vendorprofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='name',
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendorprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='vendors.vendorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
