# Generated by Django 3.2.9 on 2021-11-18 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_auto_20211117_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Name'),
        ),
    ]
