# Generated by Django 3.2.9 on 2021-11-19 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_auto_20211119_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='company_name',
            new_name='name',
        ),
    ]
